name: Deployment exercise
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: download the code
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
    lint:
        runs-on: ubuntu_latest
        needs: build
        steps:
            - name: lint
              run: npm run lint
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy code
              run: echo "Deploying......."
            


